export function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-[#f0f0f5] py-20 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-white mb-8">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-10">Effective Date: April 23, 2026</p>

        <Section title="1. Information We Collect">
          We collect: (a) account information (email, name); (b) audio recordings you upload; (c) meeting metadata generated by our AI analysis; (d) usage data (meetings processed, features used).
        </Section>

        <Section title="2. How We Use Your Data">
          We use your data to: (a) provide the Service; (b) improve our AI models using anonymized data; (c) send service-related communications; (d) comply with legal obligations.
        </Section>

        <Section title="3. Third-Party Services">
          We use the following third-party services to process your data:
          <br /><br />
          • <strong>AssemblyAI</strong> – Audio transcription and speaker identification<br />
          • <strong>Groq</strong> – AI-powered meeting analysis<br />
          • <strong>Supabase</strong> – Database and authentication<br />
          • <strong>Stripe</strong> – Payment processing<br />
          <br />
          Each third party has its own privacy policy governing their use of your data.
        </Section>

        <Section title="4. Data Retention">
          Audio recordings are retained for 30 days after processing, then deleted. Meeting metadata (summaries, action items, decisions) is retained for the life of your account. You may request deletion of your data at any time.
        </Section>

        <Section title="5. Data Security">
          We use industry-standard encryption (TLS) for data in transit and at rest. However, no method of electronic storage is 100% secure.
        </Section>

        <Section title="6. Your Rights">
          You have the right to: (a) access your data; (b) request correction of inaccurate data; (c) request deletion of your data; (d) export your data. Contact us to exercise these rights.
        </Section>

        <Section title="7. Cookies">
          We use essential cookies for authentication. We do not use tracking cookies or sell your data to advertisers.
        </Section>

        <Section title="8. Changes to This Policy">
          We will notify you of material changes to this policy via email or in-app notice.
        </Section>

        <Section title="9. Contact">
          📧 <a href="mailto:intellicaai.ai@gmail.com" className="text-purple-400 hover:underline">intellicaai.ai@gmail.com</a>
        </Section>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-xl font-semibold text-white mb-3">{title}</h2>
      <p className="text-gray-300 leading-relaxed">{children}</p>
    </div>
  )
}
